# Generated by Django 2.1.5 on 2022-05-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220520_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservacion', 'verbose_name_plural': 'reservaciones'},
        ),
    ]
